name: Dependency Diff

on:
  pull_request_target:
    branches:
      - main

jobs:
  build-main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
      - name: Use Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: node --run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: base-packages
          path: '*.tgz'
  build-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: node --run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: source-packages
          path: '*.tgz'
  diff_dependencies:
    runs-on: ubuntu-latest
    needs: [build-main, build-pr]
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: base-packages
          path: ./base-packages
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: source-packages
          path: ./source-packages
      - name: Create Diff
        uses: e18e/action-dependency-diff@d995338f3b229fe7b2cd82048df5da930f70c7c3 # v1.4.4
        with:
          base-packages: ./base-packages/*.tgz
          source-packages: ./source-packages/*.tgz
