name: Dependency Diff

on:
  pull_request:

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: main
      - name: Use Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: node --run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: base-packages
          path: '*.tgz'
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Use Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: node --run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: source-packages
          path: '*.tgz'
  diff_dependencies:
    runs-on: ubuntu-latest
    needs: [build-main, build-pr]
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: base-packages
          path: ./base-packages
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: source-packages
          path: ./source-packages
      - name: Create Diff
        uses: ./
        with:
          base-packages: ./base-packages/*.tgz
          source-packages: ./source-packages/*.tgz
