name: Dependency Diff

on:
  pull_request:

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: main
      - name: Use Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: node --run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: base-packages
          path: '*.tgz'
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Use Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: node --run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: source-packages
          path: '*.tgz'
  diff_dependencies:
    runs-on: ubuntu-latest
    needs: [build-main, build-pr]
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: base-packages
          path: ./base-packages
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: source-packages
          path: ./source-packages
      - name: Create Diff
        uses: ./
        with:
          base-packages: ./base-packages/*.tgz
          source-packages: ./source-packages/*.tgz
